Fix JRuby exception in posix run! method
NoMethodError:
undefined method `success?' for #<Process::WaitThread:0xd5c0e84 dead>

WaitThread does not have a success? method, but it does have a value
property which can be checked instead.